const mimetypes = require("./mimetypes");

const commonFields = [
  {
    title: "Labelling Type",
    attributeName: "labelingType",
    description: "Type of labelling used in resource",
    type: "customSelect",
    enum: ["Type", "Instance"],
  },
  {
    title: "Tags/ Labels",
    attributeName: "labels",
    description: "Labels included in image resource",
    type: "customSelect",
    multiple: true,
    enum: [],
  },
  {
    title: "Annotation Workflow description",
    attributeName: "annotationWorkflowDescription",
    description: "Description of image annotation workflow",
    type: "text",
  },
  {
    title: "Mislabeled Data Detection Approach",
    attributeName: "mislabeledDataDetectionApproach",
    description: "Description of approach to filter mislabeled data",
    type: "text",
  },
  {
    title: "Data generation type",
    attributeName: "dataGenerationType",
    description: "Type of data generation",
    type: "select",
    enum: ["Native Capture", "Data Augmentation", "Data Generation"],
  },
  {
    title: "Contains PII",
    attributeName: "containsPII",
    description: "Selection if data contains personal identifiable information",
    type: "boolean",
  },
];
const commonFileFields = [
  {
    title: "File Format",
    attributeName: "fileFormat",
    description: "Format of data to be transferred",
    type: "select",
    enum: mimetypes,
  },
  {
    title: "File Size",
    attributeName: "filesize",
    description: "Space occupied by files on hard drive in Megabytes",
    type: "text",
  },
];

module.exports = [
  {
    id: "auJCKcgVpPU",
    title: "Asset Administration Shell",
    priority: 10,
    fields: [
      {
        title: "Real-world entity kind",
        attributeName: "realWorldEntityKind",
        description: "Type of real world entity that the data describes",
        type: "select",
        enum: ["Type", "Instance"],
      },
      {
        title: "File formats",
        attributeName: "aasFileFormats",
        description: "Format of data to be transferred",
        type: "select",
        multiple: true,
        enum: ["coming", "soon"],
      },
      {
        title: "Interface type",
        attributeName: "aasInterfaceType",
        description: "Type of interface to data source",
        type: "text",
        enum: ["coming", "soon"],
      },
      {
        title: "Attribute Names",
        attributeName: "attributeNames",
        description: "Name of Attributes",
        type: "customSelect",
        multiple: true,
        enum: [],
      },
      {
        title: "Submodel",
        attributeName: "assSubmodel",
        description: "Submodels included in AAS",
        type: "customSelect",
        multiple: true,
        enum: [],
      },
      {
        title: "Data Specification",
        attributeName: "assDataSpecification",
        description: "Data specification templeates included in AAS component",
        type: "customSelect",
        multiple: true,
        enum: [],
      },
      {
        title: "Sensors",
        attributeName: "assSensors",
        description: "Sensor used to record data (also camera or microphone)",
        type: "customSelect",
        multiple: true,
        enum: [],
      },
      {
        title: "Derived From",
        attributeName: "derivedFrom",
        description: "Indicator of AAS was derived from other (meta-) AAS",
        type: "text",
      },
      {
        title: "Real-world process machine tool",
        attributeName: "realWorldProcessMachineTool",
        description:
          "Process conducted by the real world entity during data generation, DIN 8580 (translation)",
        type: "select",
        enum: [
          "Casting",
          "Reshaping",
          "Cutting",
          "Joining",
          "Coating",
          "Altering Material Properties",
          "Molding from the liquid state",
          "Molding from the plastic state",
          "Molding from the pulpy state",
          "Molding from the granular or powdery state",
          "Molding from the chip- or fiber-like state",
          "Molding by welding",
          "Molding from the gaseous or vaporous state",
          "Molding from the ionized state",
          "Molding by additive manufacturing",
          "Cutting",
          "Machining with geometrically determined cutting edge",
          "Machining with geometrically undefined cutting edges",
          "Removal",
          "Dismantling",
          "Cleaning",
          "Composition",
          "Filling",
          "Pressing on and in",
          "Joining by molding",
          "Joining by forming",
          "Joining by welding",
          "Joining by soldering",
          "Gluing",
          "Coating from the liquid state",
          "Coating from the plastic state",
          "Coating from the pulpy state",
          "Coating from granular or powdery state",
          "Coating by welding",
          "Coating by soldering",
          "Coating from the gaseous or vaporous state (vacuum coating)",
          "Coating from the ionized state",
          "Strengthening by forming",
          "Heat-treating ",
          "Thermo-mechanical treatment",
          "Sintering",
          "Magnetizing",
          "Irradiation",
          "Photo-chemical processes",
        ],
        multiple: true,
        fullWidth: true,
      },
    ],
  },
  {
    id: "Nmh_4vjTCkQ",
    title: "Labelled Image Data",
    priority: 10,
    fields: [
      {
        title: "Image Deduplication Approach",
        attributeName: "imageDeduplicationApproach",
        description: "Description of approach for image deduplication",
        type: "text",
      },
      {
        title: "Number of attributes",
        attributeName: "numberOfAttributes",
        description: "Number of attributes described in table",
        type: "text",
      },
      {
        title: "Number of images",
        attributeName: "numberOfImages",
        description: "Number of images in collection",
        type: "text",
      },
      {
        title: "Data Quality",
        attributeName: "dataQualityAttribute",
        description: "Number of images in collection",
        type: "text",
      },
      {
        title: "Orientation",
        attributeName: "orientation",
        description: "Image orientation ",
        type: "select",
        enum: ["Horizontal", "Vertical"],
      },
      {
        title: "Image width",
        attributeName: "imageWidth",
        description: "Width of an image (in pixels)",
        type: "text",
      },
      {
        title: "Image height",
        attributeName: "imageHeight",
        description: "Height of an image (in pixels)",
        type: "text",
      },
      {
        title: "Image Resolution",
        attributeName: "imageResolution",
        description: "Resolution of an image (in Megapixels)",
        type: "text",
      },
      ...commonFileFields,
      ...commonFields,
    ],
  },
  {
    id: "p2uFIZi0CKK",
    title: "Usage Control",
    priority: 1,
    fields: [
      {
        title: "Usage Conditions",
        attributeName: "usageConditions",
        description: "usage conditions",
        type: "customSelect",
        multiple: true,
        fullWidth: true,
        enum: [
          "Disclosure of data to third parties",
          "Determination of data usage for specified use cases",
          "Preventing the aggregation of data with competitor data",
          "Determination of the period of use",
          "Preventing the aggregation of personal data",
          "Other",
        ],
      },
      {
        title: "Policy",
        attributeName: "policy",
        description: "Policy definition",
        type: "textarea",
        fullWidth: true,
      },
      {
        title: "Disclosure of personal data allowed",
        attributeName: "DisclosureOfPersonalDataAllowed",
        description: "Disclosure of personal data allowed",
        type: "boolean",
      },
      {
        title: "Personal data anonymized",
        attributeName: "personalDataAnonymized",
        description: "Personal data anonymized",
        type: "boolean",
      },
    ],
  },
];
